import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import CatagorySlider from './components/CategorySlider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='px-6 py-2'>
          <Header />
          <CatagorySlider />
        </header>
        {children}
      </body>
    </html>
  )
}
